apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: dashboard
build:
  artifacts:
    - image: ghcr.io/do-22-23-isdm/dashboard
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: /app/
          - src: 'public/**/*.*'
            dest: /app/
  local:
    useBuildkit: true
manifests:
  rawYaml:
    - kubernetes/deployment.yaml
    - kubernetes/svc.yaml
