apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: dashboard
build:
  artifacts:
    - image: ghcr.io/do-22-23-isdm/dashboard
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: /app/
          - src: 'public/**/*.*'
            dest: /app/
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: isdm
        chartPath: infra/charts/isdm
        setValueTemplates:
          image: "{{ .IMAGE_FULLY_QUALIFIED_ghcr_io_do_22_23_isdm_dashboard }}"
portForward:
  - resourceType: service
    resourceName: dashboard
    namespace: default
    port: 80
    localPort: 3000
